"""posts_ai_summary

Revision ID: 9cbb7dcfd2f3
Revises: b962ed98ceb6
Create Date: 2026-09-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9cbb7dcfd2f3'
down_revision = 'b962ed98ceb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ai_summary')
    # ### end Alembic commands ###
