"""init_schema_24_tables

Revision ID: e2e8ae0dcb8e
Revises: 
Create Date: 2026-09-15 09:55:14.857687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2e8ae0dcb8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('school', sa.Text(), nullable=True),
    sa.Column('college', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('student_no', sa.Text(), nullable=False),
    sa.Column('real_name', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('major_id', sa.BigInteger(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='student', nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('credit', sa.Integer(), server_default='100', nullable=False),
    sa.Column('gpa_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student','reviewer','builder','admin')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active','muted','frozen')", name='ck_users_status'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('student_no')
    )
    op.create_table('ai_quotas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('daily_limit', sa.Integer(), server_default='30', nullable=False),
    sa.Column('bonus_balance', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_identities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id')
    )
    op.create_table('credit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_logs_user', 'credit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('resource','post')", name='ck_favorites_target'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id')
    )
    op.create_table('follows',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('course','user')", name='ck_follows_target'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','processing','resolved','dismissed')", name='ck_reports_status'),
    sa.CheckConstraint("target_type IN ('resource','post','comment','user')", name='ck_reports_target_type'),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_logs_user', 'score_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_llm_keys',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('model_short', sa.Text(), nullable=True),
    sa.Column('model_medium', sa.Text(), nullable=True),
    sa.Column('model_long', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('votes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('post','comment','resource')", name='ck_votes_target_type'),
    sa.CheckConstraint('value IN (1,-1)', name='ck_votes_value'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id')
    )
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('major_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('semester_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope='public' AND major_id IS NOT NULL AND owner_id IS NULL) OR (scope='personal' AND owner_id IS NOT NULL)", name='ck_courses_scope_ownership'),
    sa.CheckConstraint("scope IN ('public','personal')", name='ck_courses_scope'),
    sa.CheckConstraint("status IN ('active','pending','disabled')", name='ck_courses_status'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_major', 'courses', ['major_id'], unique=False, postgresql_where=sa.text("scope='public'"))
    op.create_index('idx_courses_owner', 'courses', ['owner_id'], unique=False, postgresql_where=sa.text("scope='personal'"))
    op.create_table('chapters',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('order_idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary_vector_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapters_course', 'chapters', ['course_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Text(), server_default='personal', nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('preview_key', sa.Text(), nullable=True),
    sa.Column('md5', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='parsing', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('pdf_textbook','ppt','word','markdown')", name='ck_documents_file_type'),
    sa.CheckConstraint("scope IN ('personal','public')", name='ck_documents_scope'),
    sa.CheckConstraint("status IN ('parsing','parsed','failed')", name='ck_documents_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_md5', 'documents', ['md5'], unique=False)
    op.create_index('idx_documents_owner', 'documents', ['owner_id'], unique=False)
    op.create_table('qa_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('search_scope', sa.Text(), nullable=False),
    sa.Column('coarse_chapters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.Text(), nullable=True),
    sa.CheckConstraint("scope IN ('personal','public')", name='ck_chunks_scope'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index('idx_chunks_course_scope', 'chunks', ['course_id', 'scope'], unique=False)
    op.create_index('idx_chunks_owner', 'chunks', ['owner_id'], unique=False, postgresql_where=sa.text("scope='personal'"))
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('board', sa.Text(), nullable=False),
    sa.Column('major_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('bounty_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ai_first_answer', sa.Text(), nullable=True),
    sa.Column('accepted_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='normal', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("board IN ('qa','experience','bounty','discuss')", name='ck_posts_board'),
    sa.CheckConstraint("status IN ('normal','featured','closed')", name='ck_posts_status'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_board', 'posts', ['board', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('review_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fav_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('download_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('pending','co_reviewing','approved','rejected')", name='ck_resources_review_status'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resources_course', 'resources', ['course_id', 'review_status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tasks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Text(), server_default='precheck', nullable=False),
    sa.Column('precheck_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assignee_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("stage IN ('precheck','co_review','final','done')", name='ck_review_tasks_stage'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_records',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('co_review','final')", name='ck_review_records_stage'),
    sa.CheckConstraint("verdict IN ('approve','reject')", name='ck_review_records_verdict'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_records')
    op.drop_table('review_tasks')
    op.drop_table('comments')
    op.drop_index('idx_resources_course', table_name='resources')
    op.drop_table('resources')
    op.drop_index('idx_posts_board', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_chunks_owner', table_name='chunks', postgresql_where=sa.text("scope='personal'"))
    op.drop_index('idx_chunks_course_scope', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('qa_logs')
    op.drop_index('idx_documents_owner', table_name='documents')
    op.drop_index('idx_documents_md5', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_chapters_course', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index('idx_courses_owner', table_name='courses', postgresql_where=sa.text("scope='personal'"))
    op.drop_index('idx_courses_major', table_name='courses', postgresql_where=sa.text("scope='public'"))
    op.drop_table('courses')
    op.drop_table('votes')
    op.drop_table('user_llm_keys')
    op.drop_table('semesters')
    op.drop_index('idx_score_logs_user', table_name='score_logs')
    op.drop_table('score_logs')
    op.drop_table('reports')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('follows')
    op.drop_table('favorites')
    op.drop_index('idx_credit_logs_user', table_name='credit_logs')
    op.drop_table('credit_logs')
    op.drop_table('auth_identities')
    op.drop_table('audit_logs')
    op.drop_table('ai_quotas')
    op.drop_table('users')
    op.drop_table('majors')
    # ### end Alembic commands ###
